<?php

return [
    'APPLICATION_REFUSED' => Lang::get('rrhh::emails_templates.APPLICATION_REFUSED'),
    'APPLICATION_ACCEPTED' => Lang::get('rrhh::emails_templates.APPLICATION_ACCEPTED'),
    'APPLICATION_INTERVIEW' => Lang::get('rrhh::emails_templates.APPLICATION_INTERVIEW'),
    'APPLICATION_RECEIVED_CANDIDATE' => Lang::get('rrhh::emails_templates.APPLICATION_RECEIVED_CANDIDATE'),
    'APPLICATION_RECEIVED_RECRUITER' => Lang::get('rrhh::emails_templates.APPLICATION_RECEIVED_RECRUITER'),
    'APPLICATION_SPONTATINIOUS_RECEIVED_CANDIDATE' => Lang::get('rrhh::emails_templates.APPLICATION_SPONTATINIOUS_RECEIVED_CANDIDATE'),
    'APPLICATION_SPONTATINIOUS_RECEIVED_RECRUITER' => Lang::get('rrhh::emails_templates.APPLICATION_SPONTATINIOUS_RECEIVED_RECRUITER'),
];
