<?php
/**
 * Created by PhpStorm.
 * User: ninidc
 * Date: 15/08/2018
 * Time: 14:18
 */

namespace Modules\ExternalApi\Transformers;


use Illuminate\Http\Resources\Json\Resource;

class ProgramCategoryTransformer extends Resource
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}