<?php
/**
 * Created by PhpStorm.
 * User: ninidc
 * Date: 16/08/2018
 * Time: 19:23
 */

namespace Modules\ExternalApi\Collections;


use Illuminate\Http\Resources\Json\ResourceCollection;

class AxeCollection extends ResourceCollection
{

    protected $fieldSearchable = [
        'id_axe',
        'id',
    ];

    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}