<?php
namespace Modules\ExternalApi\Collections;


use Illuminate\Http\Resources\Json\ResourceCollection;

class ProgramCategoryCollection extends ResourceCollection
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
